services:
  - type: web
    name: MLBP-Streamlit-App
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: $PORT
